CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  default_name VARCHAR(255),
  name_key VARCHAR(255),
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  image VARCHAR(255),
  images JSONB,
  brand VARCHAR(100),
  category_id INTEGER,
  type VARCHAR(100),
  model VARCHAR(255),
  quantity VARCHAR(100),
  offers JSONB,
  installation_available BOOLEAN DEFAULT false,
  name_uk VARCHAR(255),
  name_pl VARCHAR(255),
  description TEXT,
  description_uk TEXT,
  description_pl TEXT,
  searchable_text TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);